### PR TITLE
About Screen and Letter Browser with Next/ Prev button functionality …

### PR DESCRIPTION
**Pull request by anishapai**
…and Pause Screen 'Lettter' button functionality.

### CODE REVIEW

**Comment by imann24** [comment]
Gets cut off at certain resolutions:

image

**Comment by imann24** [comment]
Should lock horizontal scrolling (shouldn't be able to scroll sideways): 

image

image

**Comment by imann24** [comment]
@anishapai This looks really good! Just a few small fixes to make

**Review by imann24 — CHANGES_REQUESTED** [review]
Just a couple changes needed. Generally looks really good!

**Comment by anishapai** [comment]
Fixed these changes on the AboutScreen_LetterBrowser branch.. unsure how to push that

**Comment by imann24** [comment]
@anishapai if you push to the same branch w/ an open pull request, it should auto update. I'll double check in Unity to verify

**Comment by imann24** [comment]
@anishapai looks great! Will merge now

**Pull request merged**
