### PR TITLE
EnemyLadderLogic

### PR DESCRIPTION
**Pull request by adaxz**

### CODE REVIEW

**Comment by imann24** [comment]
@adaxz There are a lot of merge conflicts when I attempt to merge into master. Do you mind looking into resolving those?

**Review by imann24 — CHANGES_REQUESTED** [review]
Merge conflicts need to be resolved

**Comment by adaxz** [comment]
Sorry, I don't really understand the conflicts. Is there any suggestion on how to resolve conflicts in general?

**Comment by imann24** [comment]
@adaxz this document should give a brief rundown: https://help.github.com/articles/resolving-a-merge-conflict-on-github/. Let me know what questions you have after reviewing

**Comment by imann24** [comment]
@adaxz looks good on the conflicts! More generally, I think this code is based around the old map scene (Scene2). 

The tricky part is that we don't have the Enemy character implemented at all into the new scenes (Map1.unity through Map10.unity) so it's a little hard to test. But I would assume some adjustments have to be made to the overall enemy movement logic before it can work in the new map system. If you want to take a look at that, let me know. 

Otherwise, we can merge this pull request as is and revisit the feature once the shadow figure has been added into the new map system

**Pull request closed without merging**
