### PR TITLE
About Screen 

### PR DESCRIPTION
**Pull request by anishapai**
With Credits, a backbutton and a version number

### CODE REVIEW

**Comment by imann24** [comment]
From the wireframe, the about screen just has a button to the "Credits" screen. Should confer with @mhollister92 to confirm what spec she had in mind: 
image

**Comment by imann24** [comment]
@anishapai Sounds as though you're up to spec w/ the credits. My only other request is to put a version number somewhere on the screen. You can set it to v0.0.5 for now.

**Comment by anishapai** [comment]
gotcha, underway.

**Comment by anishapai** [comment]
@imann24 done!

**Pull request merged**
